"use strict";
// Generated by Endor Labs Agent Kit. Do not hand-edit installed extension cache copies.
// endor_agent_kit_managed=true host=vscode artifact=extension-entry
const vscode = require("vscode");

function activate(context) {
  const didChange = new vscode.EventEmitter();
  context.subscriptions.push(didChange);
  context.subscriptions.push(
    vscode.lm.registerMcpServerDefinitionProvider('endor-cli-tools', {
      onDidChangeMcpServerDefinitions: didChange.event,
      provideMcpServerDefinitions: async () => [
        new vscode.McpStdioServerDefinition(
          'endor-cli-tools',
          'npx',
          ["-y", "endorctl", "ai-tools", "mcp-server"]
        )
      ],
      resolveMcpServerDefinition: async (server) => server
    })
  );
}

function deactivate() {}

module.exports = { activate, deactivate };
