"""Shared helpers for generated plugin package publication."""

from __future__ import annotations

from importlib import metadata

PLUGIN_NAME = "endor-labs-agent-kit"
PLUGIN_DISPLAY_NAME = "Endor Labs Agent Kit"
PLUGIN_VERSION_FALLBACK = "0.1.0"


def package_version() -> str:
    """Return the installed package version used for generated plugin packages."""

    try:
        return metadata.version("endor-labs-agent-kit")
    except metadata.PackageNotFoundError:
        return PLUGIN_VERSION_FALLBACK


def logo_svg() -> str:
    """Return the minimal Endor Agent Kit plugin logo."""

    return "\n".join([
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" role="img" aria-label="Endor Labs Agent Kit">',
        '  <rect width="128" height="128" rx="24" fill="#111827"/>',
        '  <path d="M32 36h64v14H49v17h39v14H49v17h47v14H32z" fill="#ffffff"/>',
        '  <path d="M81 32h18v64h-18z" fill="#4F46E5" opacity=".9"/>',
        "</svg>",
        "",
    ])


def plugin_packages_readme() -> str:
    """Return the generated plugin packages README."""

    return "\n".join([
        "# Endor Labs Agent Kit Plugin Packages",
        "",
        "<!-- Generated by Endor Labs Agent Kit. Do not hand-edit. -->",
        "",
        "This directory contains generated plugin package artifacts. Generate or",
        "refresh them with:",
        "",
        "```bash",
        "endor-agent-kit publish source/agents/*/recipe.yaml --dest . --prune --include-plugins",
        "```",
        "",
        "Current generated package slices:",
        "",
        "- `codex/endor-labs-agent-kit/`: Codex plugin package with setup skill,",
        "  Codex workflow skills, bundled custom-agent TOML files, installer script,",
        "  and local marketplace metadata under `codex/.agents/plugins/marketplace.json`.",
        "- `claude/endor-labs-agent-kit/`: Claude Code plugin package with setup skill,",
        "  Claude Code workflow agents, minimal assets, and marketplace metadata under",
        "  `.claude-plugin/marketplace.json` and `claude/.claude-plugin/marketplace.json`.",
        "",
        "Gemini remains a planned release-critical host package. The Gemini slice",
        "should generate a release archive rooted at `plugins/gemini/endor-labs-agent-kit`",
        "so `gemini-extension.json` is at the archive root while the repository keeps",
        "all generated host packages together.",
        "",
    ])
