name: endor-package-risk-summary-developer-edition
config:
  type: cloud
  networking:
    type: limited
    allowed_hosts:
    - https://api.endorlabs.com
    allow_mcp_servers: true
    allow_package_managers: false
